jumlahB = 3
hargaB = 25000
totalB = jumlahB * hargaB
print("Total harga buku = Rp" + str(totalB))
jumlahP = 2
hargaP = 8000
totalP = jumlahP * hargaP
print("Total harga pulpen = Rp" + str(totalP))
jumlahF = 1
hargaF = 75000
totalF = jumlahF * hargaF
print("Total harga FlashDisk = Rp" + str(totalF))
totalSdiskon = totalB + totalP + totalF
print("Total sebelum diskon = Rp" + str(totalSdiskon))
print("Kemudian Udin mendapatkan promo awal semester sebesar 10%, dan dikenakan Pajak Pertambahan Nilai(PPN) sebesar 11%.")
diskon = totalSdiskon * 0.1
setelahdiskon = totalSdiskon - diskon
print("Total setelah diskon = Rp" + str(setelahdiskon))
ppn = setelahdiskon * 0.11
setelahppn = setelahdiskon + ppn
print("Total Pajak Pertambahan Nilai (PPN) = Rp" + str(ppn))
print("Total setelah dikenakan Pajak Pertambahan Nilai (PPN) = Rp" + str(setelahppn))
total = setelahppn
print("Total pembayaran = Rp" + str(total))
print("Uang yang Udin Bayar = Rp200.000")
uangUdin = 200000
kembalian = uangUdin - total
print("Total kembalian uang Udin = Rp" + str(kembalian))