hargaBuku = 25000
jumlahBuku = 3
totalBuku = hargaBuku * jumlahBuku
hargaPulpen = 8000
jumlahPulpen = 2
totalPulpen = hargaPulpen * jumlahPulpen
hargaFlashdisk = 75000
jumlahFlashdisk = 1
totalFlashdisk = hargaFlashdisk * jumlahFlashdisk
totalSebelumDiskon = totalBuku + totalPulpen + totalFlashdisk
diskon = totalSebelumDiskon * 10 / 100
setelahDiskon = totalSebelumDiskon - diskon
ppn = setelahDiskon * 11 / 100
totalBayar = setelahDiskon + ppn
uangTunai = 200000
kembalian = uangTunai - totalBayar
print("a) Total harga buku = Rp" + str(totalBuku))
print("b) Total harga pulpen = Rp" + str(totalPulpen))
print("c) Total harga flashdisk = Rp" + str(totalFlashdisk))
print("d) Total harga seluruh barang sebelum diskon = Rp" + str(totalSebelumDiskon))
print("e) Besarnya diskon 10% = Rp" + str(diskon))
print("f) Harga barang setelah diskon = Rp" + str(setelahDiskon))
print("g) Besarnya PPN 11% = Rp" + str(ppn))
print("h) Total pembayaran setelah pajak = Rp" + str(totalBayar))
print("i) Uang kembalian = Rp" + str(kembalian))
